/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUtilisateursRouteImport } from './routes/admin.utilisateurs'
import { Route as AdminStatistiques2RouteImport } from './routes/admin.statistiques2'
import { Route as AdminStatistiques1RouteImport } from './routes/admin.statistiques1'
import { Route as AdminStatistiquesRouteImport } from './routes/admin.statistiques'
import { Route as ProtectedRendezVousRouteImport } from './routes/_protected/rendez-vous'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/admin/utilisateurs',
  path: '/admin/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatistiques2Route = AdminStatistiques2RouteImport.update({
  id: '/admin/statistiques2',
  path: '/admin/statistiques2',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatistiques1Route = AdminStatistiques1RouteImport.update({
  id: '/admin/statistiques1',
  path: '/admin/statistiques1',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatistiquesRoute = AdminStatistiquesRouteImport.update({
  id: '/admin/statistiques',
  path: '/admin/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRendezVousRoute = ProtectedRendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/rendez-vous': typeof ProtectedRendezVousRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/admin/statistiques1': typeof AdminStatistiques1Route
  '/admin/statistiques2': typeof AdminStatistiques2Route
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/rendez-vous': typeof ProtectedRendezVousRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/admin/statistiques1': typeof AdminStatistiques1Route
  '/admin/statistiques2': typeof AdminStatistiques2Route
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/_protected/rendez-vous': typeof ProtectedRendezVousRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/admin/statistiques1': typeof AdminStatistiques1Route
  '/admin/statistiques2': typeof AdminStatistiques2Route
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/rendez-vous'
    | '/admin/statistiques'
    | '/admin/statistiques1'
    | '/admin/statistiques2'
    | '/admin/utilisateurs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/rendez-vous'
    | '/admin/statistiques'
    | '/admin/statistiques1'
    | '/admin/statistiques2'
    | '/admin/utilisateurs'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/about'
    | '/contact'
    | '/services'
    | '/_protected/rendez-vous'
    | '/admin/statistiques'
    | '/admin/statistiques1'
    | '/admin/statistiques2'
    | '/admin/utilisateurs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  AdminStatistiquesRoute: typeof AdminStatistiquesRoute
  AdminStatistiques1Route: typeof AdminStatistiques1Route
  AdminStatistiques2Route: typeof AdminStatistiques2Route
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/utilisateurs': {
      id: '/admin/utilisateurs'
      path: '/admin/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistiques2': {
      id: '/admin/statistiques2'
      path: '/admin/statistiques2'
      fullPath: '/admin/statistiques2'
      preLoaderRoute: typeof AdminStatistiques2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistiques1': {
      id: '/admin/statistiques1'
      path: '/admin/statistiques1'
      fullPath: '/admin/statistiques1'
      preLoaderRoute: typeof AdminStatistiques1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistiques': {
      id: '/admin/statistiques'
      path: '/admin/statistiques'
      fullPath: '/admin/statistiques'
      preLoaderRoute: typeof AdminStatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/rendez-vous': {
      id: '/_protected/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/rendez-vous'
      preLoaderRoute: typeof ProtectedRendezVousRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedRendezVousRoute: typeof ProtectedRendezVousRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedRendezVousRoute: ProtectedRendezVousRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  AdminStatistiquesRoute: AdminStatistiquesRoute,
  AdminStatistiques1Route: AdminStatistiques1Route,
  AdminStatistiques2Route: AdminStatistiques2Route,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
